server:
  port: 8080
spring:
  #  cloud:
  #    discovery:
  #      client:
  #        simple:
  #          instances:
  #            backend:
  #              - instanceId: backend1
  #                serviceId: backend
  #                host: localhost
  #                port: 8080
  #                secure: false #true?
  kafka:
    consumer:
      bootstrap-servers: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
      auto-offset-reset: latest
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="XWAX5C4GBM3GYFGL" password="8MDlm53MB00dAjk5pvtko26JYU0p1+PqFC4pfjTVubk3OlqQvKf93VsuYpZQXysS";
      group-id: group-21bb9c95-a2c8-4ea9-bffa-a9ae28ed9aa3
    producer:
      bootstrap-servers: pkc-lq8gm.westeurope.azure.confluent.cloud:9092
      #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="XWAX5C4GBM3GYFGL" password="8MDlm53MB00dAjk5pvtko26JYU0p1+PqFC4pfjTVubk3OlqQvKf93VsuYpZQXysS";
maven:
  username: maven
  password: qmuzGEmgr7UWMk!FG3ToJM
  ignoreMessages: false
  tournamentId: FLNyT_Jgo1
  kafka:
    topicGameStarted: cc.battleships.game.started
    topicGameEnded: cc.battleships.game.ended
    topicRoundStarted: cc.battleships.round.started
    topicRoundEnded: cc.battleships.round.ended
    topicRoundShoot: cc.battleships.shot
  http:
    scheme: http
    host: prod.battleships.cc
    port: 80
