package com.tech.challenge.maven.kafka.events;

// This class is generated by the jsonCodeGen bean template (bean.txt), changes have to implement there


import java.util.List;

/**
 * Schema to describe an ended game.
 */
public class BattleshipTemplate {

    private int width;
    private int height;
    private List<Cell> canvas;
}

