package com.tech.challenge.maven.kafka.events;

// This class is generated by the jsonCodeGen bean template (bean.txt), changes have to implement there


import lombok.ToString;

/**
 * Schema to describe a shot
 */
@ToString
public class ShotFired {
    
    
    /**
     * game id
     */
    private String gameId;
    
    public String getGameId () { return this.gameId; }

    public void setGameId (String gameId) {
        this.gameId = gameId;
        
    }

    
    /**
     * round number
     */
    private Integer roundNo;
    
    public Integer getRoundNo () { return this.roundNo; }

    public void setRoundNo (Integer roundNo) {
        this.roundNo = roundNo;
        
    }

    
    /**
     * id of the tournament
     */
    private String tournamentId;
    
    public String getTournamentId () { return this.tournamentId; }

    public void setTournamentId (String tournamentId) {
        this.tournamentId = tournamentId;
        
    }

    
    /**
     * x coordinate of the axis
     */
    private Integer x;
    
    public Integer getX () { return this.x; }

    public void setX (Integer x) {
        this.x = x;
        
    }

    
    /**
     * y coordinate of the axis
     */
    private Integer y;
    
    public Integer getY () { return this.y; }

    public void setY (Integer y) {
        this.y = y;
        
    }

    

    @Override
    public boolean equals(Object obj) {
        if (obj==null) return false;
        if ( ! (obj instanceof ShotFired)) return false;

        ShotFired _typeInst = (ShotFired) obj;
       // handling of non-array-types
    
        String _gameId = _typeInst.getGameId ();
        if (this.gameId == null && _gameId != null) return false;
        if (this.gameId != null) {
            if (!this.gameId.equals(_gameId)) return false;
        }
    
        Integer _roundNo = _typeInst.getRoundNo ();
        if (this.roundNo == null && _roundNo != null) return false;
        if (this.roundNo != null) {
            if (!this.roundNo.equals(_roundNo)) return false;
        }
    
        String _tournamentId = _typeInst.getTournamentId ();
        if (this.tournamentId == null && _tournamentId != null) return false;
        if (this.tournamentId != null) {
            if (!this.tournamentId.equals(_tournamentId)) return false;
        }
    
        Integer _x = _typeInst.getX ();
        if (this.x == null && _x != null) return false;
        if (this.x != null) {
            if (!this.x.equals(_x)) return false;
        }
    
        Integer _y = _typeInst.getY ();
        if (this.y == null && _y != null) return false;
        if (this.y != null) {
            if (!this.y.equals(_y)) return false;
        }
    
       // handling of array-types
    
        return true;
    }

}

